/* 새 시뮬레이션이 생기면 여기에 한 줄만 추가하세요. 순서 = 만든 순서. */
const SIMS=[
 {slug:'flight_simulation',title:'항공기 풍동 시뮬레이션',copy:'받음각을 올리면 양력이 커지다가, 어느 순간 실속한다',mobileOk:true,note:'처음 만든 것입니다. 조잡하고 깔끔하지 않습니다 — 디자인도 코딩도 모르던 사람이 만들었으니까요. 그런데 실행해보면 비행 조건과 궤도 유지를 충실히 시뮬레이션합니다. 제가 물리교사이기 때문입니다. 여러분도 전공 지식이 가장 큰 무기입니다.'},
 {slug:'newton_cannon',title:'뉴턴의 대포',copy:'포탄과 사과와 달은 지금 이 순간에도 지구를 향해 자유 낙하한다',mobileOk:true},
 {slug:'mars',title:'화성 전이',copy:'발사 창이 닫히면 화성에 도달할 수 없다',mobileOk:true},
 {slug:'circuit_simulation',title:'전기회로 시뮬레이터',copy:'원하는 대로 전기 회로를 그리고 눈으로 확인한다',mobileOk:true},
 {slug:'mechanics_simulation',title:'고전역학 시뮬레이터',copy:'칠판에 그리던 도르래와 용수철을 실시간으로 시뮬레이션하다',mobileOk:true,note:'도메인 지식이 있다면 디자인과 기능은 AI가 결국엔 만들어줍니다. - 누구나 할 수 있습니다. 우리 모두는 무궁한 가능성을 가지고 있습니다.'}
];
const tabs=document.querySelector('#sim-tabs'),panel=document.querySelector('#sim-panel');
const simUrl=s=>`https://shy.ai.kr/${s.slug}/`;
function renderTabs(){SIMS.forEach((s,i)=>{const b=document.createElement('button');b.className='sim-tab';b.type='button';b.id=`tab-${s.slug}`;b.role='tab';b.dataset.simSlug=s.slug;b.setAttribute('aria-controls',`panel-${s.slug}`);b.setAttribute('aria-selected',String(i===0));b.tabIndex=i===0?0:-1;const img=document.createElement('img');img.src=`assets/sim-${s.slug}-thumb.webp`;img.alt='';const label=document.createElement('span');label.textContent=s.title;b.append(img,label);b.addEventListener('click',()=>select(i));b.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();let n=e.key==='Home'?0:e.key==='End'?SIMS.length-1:(i+(e.key==='ArrowRight'?1:-1)+SIMS.length)%SIMS.length;select(n);tabs.children[n].focus()});tabs.append(b)});select(0)}
function select(i){[...tabs.children].forEach((b,n)=>{b.setAttribute('aria-selected',String(n===i));b.tabIndex=n===i?0:-1});renderPanel(SIMS[i])}
function renderPanel(s){panel.innerHTML='';const stage=document.createElement('div');stage.className='sim-stage';stage.id=`panel-${s.slug}`;stage.role='tabpanel';stage.setAttribute('aria-labelledby',`tab-${s.slug}`);const img=document.createElement('img');img.src=`assets/sim-${s.slug}.webp`;img.alt=`${s.title} 실행 화면`;const overlay=document.createElement('div');overlay.className='sim-overlay';overlay.innerHTML=`<h3>${s.title}</h3><p>${s.copy}</p>${s.note?`<p>${s.note}</p>`:''}<div class="sim-actions"><button class="button" type="button">▶ 직접 사용해보기</button><a class="button secondary" href="${simUrl(s)}" target="_blank" rel="noopener">새 탭에서 열기</a></div><p class="sim-status" role="status"></p>`;stage.append(img,overlay);panel.append(stage);overlay.querySelector('button').addEventListener('click',()=>activate(s,stage))}
async function activate(s,stage){if(matchMedia('(max-width:700px)').matches){window.open(simUrl(s),'_blank','noopener');return}const status=stage.querySelector('.sim-status');status.textContent='연결 상태를 확인하고 있습니다.';try{const r=await fetch(simUrl(s),{method:'HEAD',cache:'no-store'});if(!r.ok)throw new Error();stage.innerHTML='';stage.classList.add('is-active');const exit=document.createElement('button');exit.type='button';exit.className='embed-exit';exit.textContent='↩ 조작 종료';const viewport=document.createElement('div');viewport.className='sim-viewport';const frame=document.createElement('iframe');frame.className='sim-frame';frame.title=`${s.title} 직접 조작`;frame.src=simUrl(s);exit.addEventListener('click',()=>renderPanel(s));frame.addEventListener('load',()=>frame.focus());viewport.append(frame);stage.append(exit,viewport)}catch{status.innerHTML=`지금은 열 수 없습니다. <a href="${simUrl(s)}" target="_blank" rel="noopener">새 탭에서 열어보기 →</a>`}}
const root=document.documentElement,toggle=document.querySelector('#theme-toggle');const saved=localStorage.getItem('theme');if(saved)root.dataset.theme=saved;else if(matchMedia('(prefers-color-scheme:dark)').matches)root.dataset.theme='dark';toggle.addEventListener('click',()=>{root.dataset.theme=root.dataset.theme==='dark'?'light':'dark';localStorage.setItem('theme',root.dataset.theme)});
const emailLink=document.querySelector('#email'),copyButton=document.querySelector('#copy-email'),copyStatus=document.querySelector('#copy-status');
copyButton.remove();copyStatus.className='email-help';copyStatus.textContent='이메일 주소를 누르면 클립보드에 복사됩니다.';emailLink.classList.add('copy-email');emailLink.setAttribute('aria-describedby','copy-status');
const toast=document.createElement('div');toast.className='toast';toast.setAttribute('role','status');toast.setAttribute('aria-live','polite');toast.setAttribute('aria-atomic','true');document.body.append(toast);let toastTimer;
function showToast(message){toast.textContent=message;toast.classList.add('is-visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('is-visible'),2400)}
emailLink.addEventListener('click',async event=>{event.preventDefault();const email=emailLink.textContent.trim();let copied=false;try{await navigator.clipboard.writeText(email);copied=true}catch{const input=document.createElement('textarea');input.value=email;input.setAttribute('readonly','');input.style.position='fixed';input.style.opacity='0';document.body.append(input);input.select();input.setSelectionRange(0,input.value.length);copied=document.execCommand('copy');input.remove()}showToast(copied?'이메일 주소를 클립보드에 복사했습니다.':'복사하지 못했습니다. 이메일 주소를 길게 눌러 복사해 주세요.')});
[['#webapps','각 항목을 누르면 제작 배경과 실제 화면을 볼 수 있습니다.'],['#faq','궁금한 질문을 누르면 답변이 펼쳐집니다.']].forEach(([selector,message])=>{const section=document.querySelector(selector),hint=document.createElement('p');section.classList.add('accordion-section');hint.className='accordion-hint';hint.textContent=message;section.querySelector('h2').after(hint)});
const career=document.querySelector('#career'),careerGrid=career.querySelector('.grid');careerGrid.className='career-reveal';careerGrid.setAttribute('aria-label','주요 이력');careerGrid.innerHTML='<table class="career-table"><tbody><tr><th scope="row">2020 - 2021</th><td>충북대학교 물리교육과 MBL을 활용한 실험 수업 조교</td></tr><tr><th scope="row">2020 - 2021</th><td>충북대학교 과학영재교육원 담임교사</td></tr><tr><th scope="row">2023</th><td>「MBL을 활용한 전기 실험 및 사례 나눔」 연수강사</td></tr><tr><th scope="row">2023 - 2024, 2026</th><td>인천남부영재교육원 지도강사</td></tr><tr><th scope="row">2026</th><td>「AI 에이전트 개발 프로젝트 전문가과정」 직무연수 수료 및 프로젝트 우수상 수상</td></tr><tr><th scope="row">2026.07–08</th><td>「2026 인공지능 활용 선도교사 연수」 지도강사</td></tr></tbody></table>';
if('IntersectionObserver' in window){const careerObserver=new IntersectionObserver(entries=>{if(!entries.some(entry=>entry.isIntersecting))return;careerGrid.classList.add('is-visible');careerObserver.disconnect()},{threshold:.2});careerObserver.observe(careerGrid)}else{careerGrid.classList.add('is-visible')}
renderTabs();
