/* 새 시뮬레이션이 생기면 여기에 한 줄만 추가하세요. 순서 = 만든 순서. */
const SIMS=[
 {slug:'flight_simulation',title:'항공기 풍동 시뮬레이션',copy:'받음각을 올리면 양력이 커지다가, 어느 순간 실속한다',mobileOk:true,note:'처음 만든 것입니다. 조잡하고 깔끔하지 않습니다 — 디자인도 코딩도 모르던 사람이 만들었으니까요. 그런데 돌려보면 비행 조건과 궤도 유지를 충실히 시뮬레이션합니다. 제가 물리교사이기 때문입니다.'},
 {slug:'newton_cannon',title:'뉴턴의 대포',copy:'속도를 조금씩 올리다 보면, 떨어지던 포탄이 궤도에 오른다',mobileOk:true},
 {slug:'mars',title:'화성 전이',copy:'위상각 44°를 놓치면, 화성은 그냥 지나간다',mobileOk:true},
 {slug:'circuit_simulation',title:'전기회로 시뮬레이터',copy:'회로를 그리고 값을 넣으면 과도응답이 그려진다',mobileOk:true},
 {slug:'mechanics_simulation',title:'고전역학 시뮬레이터',copy:'칠판에 그리던 도르래와 용수철을, 끌어다 놓고 돌려본다',mobileOk:true}
];
const tabs=document.querySelector('#sim-tabs'),panel=document.querySelector('#sim-panel');
const simUrl=s=>`https://sehunyang.github.io/${s.slug}/`;
function renderTabs(){SIMS.forEach((s,i)=>{const b=document.createElement('button');b.className='sim-tab';b.type='button';b.id=`tab-${s.slug}`;b.role='tab';b.dataset.simSlug=s.slug;b.setAttribute('aria-controls',`panel-${s.slug}`);b.setAttribute('aria-selected',String(i===0));b.tabIndex=i===0?0:-1;const img=document.createElement('img');img.src=`assets/sim-${s.slug}-thumb.webp`;img.alt='';const label=document.createElement('span');label.textContent=s.title;b.append(img,label);b.addEventListener('click',()=>select(i));b.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();let n=e.key==='Home'?0:e.key==='End'?SIMS.length-1:(i+(e.key==='ArrowRight'?1:-1)+SIMS.length)%SIMS.length;select(n);tabs.children[n].focus()});tabs.append(b)});select(0)}
function select(i){[...tabs.children].forEach((b,n)=>{b.setAttribute('aria-selected',String(n===i));b.tabIndex=n===i?0:-1});renderPanel(SIMS[i])}
function renderPanel(s){panel.innerHTML='';const stage=document.createElement('div');stage.className='sim-stage';stage.id=`panel-${s.slug}`;stage.role='tabpanel';stage.setAttribute('aria-labelledby',`tab-${s.slug}`);const img=document.createElement('img');img.src=`assets/sim-${s.slug}.webp`;img.alt=`${s.title} 실행 화면`;const overlay=document.createElement('div');overlay.className='sim-overlay';overlay.innerHTML=`<h3>${s.title}</h3><p>${s.copy}</p>${s.note?`<p>${s.note}</p>`:''}<div class="sim-actions"><button class="button" type="button">▶ 직접 조작해보기</button><a class="button secondary" href="${simUrl(s)}" target="_blank" rel="noopener">새 탭에서 열기</a></div><p class="sim-status" role="status"></p>`;stage.append(img,overlay);panel.append(stage);overlay.querySelector('button').addEventListener('click',()=>activate(s,stage))}
async function activate(s,stage){if(matchMedia('(max-width:700px)').matches){window.open(simUrl(s),'_blank','noopener');return}const status=stage.querySelector('.sim-status');status.textContent='연결 상태를 확인하고 있습니다.';try{const r=await fetch(simUrl(s),{method:'HEAD',cache:'no-store'});if(!r.ok)throw new Error();stage.innerHTML='';stage.classList.add('is-active');const exit=document.createElement('button');exit.type='button';exit.className='embed-exit';exit.textContent='↩ 조작 종료';const viewport=document.createElement('div');viewport.className='sim-viewport';const frame=document.createElement('iframe');frame.className='sim-frame';frame.title=`${s.title} 직접 조작`;frame.src=simUrl(s);exit.addEventListener('click',()=>renderPanel(s));frame.addEventListener('load',()=>frame.focus());viewport.append(frame);stage.append(exit,viewport)}catch{status.innerHTML=`지금은 열 수 없습니다. <a href="${simUrl(s)}" target="_blank" rel="noopener">새 탭에서 열어보기 →</a>`}}
const root=document.documentElement,toggle=document.querySelector('#theme-toggle');const saved=localStorage.getItem('theme');if(saved)root.dataset.theme=saved;else if(matchMedia('(prefers-color-scheme:dark)').matches)root.dataset.theme='dark';toggle.addEventListener('click',()=>{root.dataset.theme=root.dataset.theme==='dark'?'light':'dark';localStorage.setItem('theme',root.dataset.theme)});
document.querySelector('#copy-email').addEventListener('click',async()=>{const email='sehun2488@ice.go.kr',status=document.querySelector('#copy-status');try{await navigator.clipboard.writeText(email);status.textContent='이메일 주소를 복사했습니다.'}catch{const range=document.createRange();range.selectNodeContents(document.querySelector('#email'));const sel=getSelection();sel.removeAllRanges();sel.addRange(range);status.textContent='주소를 선택했습니다. 복사해 주세요.'}});
renderTabs();
